country_to_eng={'Malawi': 'Malawi',
             'Ísland': 'Iceland',
             'Sénégal': 'Senegal',
             'Cameroon;Cameroun': 'Cameroon',
             'New Zealand': 'New Zealand',
             'Tchad / تشاد': 'Chad',
             'Japan': 'Japan',
             None: None,
             'Uzbekistan': 'Uzbekistan',
             'Israel': 'Israel',
             'British Virgin Islands': 'British Virgin Islands',
             'Česká republika': 'Czechia',
             'Venezuela': 'Venezuela',
             'Suomi': 'Suomi',
             "Timor-Leste; Timor Lorosa'e": 'Timor-Leste',
             'Bangladesh': 'Bangladesh',
             'Guyana': 'Guyana',
             'Hrvatska': 'Croatia',
             'Монгол Улс': 'Mongolia',
             'Azerbaijan': 'Azerbaijan',
             'Mexico': 'Mexico',
             'UAE': 'UAE',
             'Liechtenstein': 'Liechtenstein',
             'Bermuda': 'Bermuda',
             'Chile': 'Chile',
             'Malta': 'Malta',
             'Sri Lanka': 'Sri Lanka',
             'Canada': 'Canada',
             'Shqipëria': 'Albania',
             'Ghana': 'Ghana',
             'République Démocratique du Congo': 'Democratic Republic of the Congo',
             'Indonesia': 'Indonesia',
             'Singapore': 'Singapore',
             'Egypt': 'Egypt',
             'Somalia / الصومال': 'Somalia',
             'Saudi': 'Saudi',
             'Беларусь': 'Belarus',
             'República Dominicana': 'Dominican Republic',
             'Vietnam': 'Vietnam',
             'Laos': 'Laos',
             'Italy': 'Italy',
             'Jamaika': 'Jamaika',
             'Bhutan': 'Bhutan',
             'Guatemala': 'Guatemala',
             'Botswana': 'Botswana',
             'Nigeria': 'Nigeria',
             'Paraguay': 'Paraguay',
             'Fiji': 'Fiji',
             'پاکستان': 'Pakistan',
             'Việt Nam': 'Vietnam',
             'البحرين': 'Bahrain',
             'Tajikistan': 'Tajikistan',
             'Colombia': 'Colombia',
             'Myanmar': 'Myanmar',
             'South Africa': 'South Africa',
             'Austria': 'Austria',
             'ישראל': 'Israel',
             'Sūriyya سوريا': 'Syria',
             'قطر Qatar': 'Qatar',
             'Grenada': 'Grenada',
             'Hungary': 'Hungary',
             'Crna Gora': 'Montenegro',
             'ประเทศไทย': 'Thailand',
             'Switzerland': 'Switzerland',
             'República de El Salvador': 'El Salvador',
             'Spain': 'Spain',
             'السودان \u200eal-Sūdān': 'Sudan',
             'Україна': 'Ukraine',
             'Czechia': 'Czechia',
             '대한민국': 'South Korea',
             'Georgia': 'Georgia',
             'Bolivia': 'Bolivia',
             'China 中国': 'China',
             'Pakistan': 'Pakistan',
             'Togo': 'Togo',
             '북조선': 'North Korea',
             'Philippines': 'Philippines',
             'Romania': 'Romania',
             'Zambia': 'Zambia',
             'Tanzania': 'Tanzania',
             'Mozambique': 'Mozambique',
             'France': 'France',
             'Jordan / الأُرْدُن': 'Jordan',
             'Kyrgyzstan': 'Kyrgyzstan',
             'Rwanda': 'Rwanda',
             'Mauritius': 'Mauritius',
             'Bénin': 'Benin',
             "Côte d'Ivoire": 'Cote dIvoire',
             'Brunei Darussalam': 'Brunei',
             'Guinée': 'Guinea',
             'Norway': 'Norway',
             'USA': 'USA',
             'Namibia': 'Namibia',
             'Kuwait / الكويت': 'Kuwait',
             'Türkmenistan': 'Turkmenistan',
             'Cyprus': 'Cyprus',
             'Guernsey': 'Guernsey',
             'Burundi': 'Burundi',
             'سلطنة عُمان Oman': 'Oman',
             'China': 'China',
             'اليَمَن al-Yaman': 'Yaman',
             'Tonga': 'Tonga',
             'Panama': 'Panama',
             'United Kingdom': 'UK',
             'Nepal': 'Nepal',
             'Iraq': 'Iraq',
             'España': 'Spain',
             'Polska': 'Polska',
             'Honduras': 'Honduras',
             'Malaysia': 'Malaysia',
             'Georgia / საქართველო': 'Georgia',
             'ایران': 'Iran',
             'Jersey': 'Jersey',
             'تونس': 'Tunisia',
             'Burkina Faso': 'Burkina Faso',
             'Angola': 'Angola',
             'Greece': 'Greece',
             'Monaco': 'Monaco',
             'Føroyar/Færøerne': 'Faroe Islands',
             'Belarus': 'Belarus',
             'Peru': 'Peru',
             'Turkey': 'Turkey',
             'Algeria': 'Algeria',
             'الجزائر': 'Algeria',
             'United Arab Emirates': 'UAE',
             'India': 'India',
             'Argentina': 'Argentina',
             'Ecuador': 'Ecuador',
             'Vanuatu': 'Vanuatu',
             'San Marino': 'San Marino',
             '日本 (Japan)': 'Japan',
             'Cabo Verde': 'Cape Verde',
             'République du Congo': 'Republic of the Congo',
             'Lesotho': 'Lesotho',
             'Slovensko': 'Slovakia',
             'Uruguay': 'Uruguay',
             'България': 'Bulgaria',
             'Bosna i Hercegovina': 'Bosnia and Herzegovina',
             'Cambodia': 'Cambodia',
             'Italia': 'Italy',
             'Papua New Guinea': 'Papua New Guinea',
             'Kenya': 'Kenya',
             'Serbia': 'Serbia',
             'Sverige': 'Sweden',
             'Iran': 'Iran',
             'South Sudan': 'South Sudan',
             'Magyarország': 'Hungary',
             'Gibraltar': 'Gibraltar',
             'Danmark': 'Danmark',
             'Cuba': 'Cuba',
             'Libya / ليبيا': 'Libya',
             'Slovenija': 'Slovenia',
             'Marshall Islands': 'Marshall Islands',
             'Russia': 'Russia',
             'Egypt / مصر': 'Egypt',
             'Κύπρος': 'Cyprus',
             'Uganda': 'Uganda',
             'Latvija': 'Latvia',
             'Zimbabwe': 'Zimbabwe',
             'لبنان  Lebanon': 'Lebanon',
             'Thailand': 'Thailand',
             'Liberia': 'Liberia',
             'Србија (Serbia)': 'Serbia',
             'Costa Rica': 'Costa Rica',
             'UK': 'UK',
             'Madagascar': 'Madagascar',
             'Maroc': 'Morocco',
             'Portugal': 'Portugal',
             'Eesti': 'Estonia',
             'Cook Islands': 'Cook Islands',
             'Ethiopia': 'Ethiopia',
             'Ελλάδα': 'Greece',
             'België - Belgique - Belgien': 'Belgium',
             'Luxembourg': 'Luxembourg',
             'Österreich': 'Austria',
             'Kalaallit Nunaat': 'Greenland',
             'Comores;ﺍﻟﻘﻤﺮي;Komori': 'Comoros',
             'Македонија': 'North Macedonia',
             'Maldives': 'Maldives',
             'Syria': 'Syria',
             ' ': '',
             'Niger': 'Niger',
             'Россия': 'Russia',
             'Palestinian Territory': 'Palestinian Territory',
             'Swaziland': 'Eswatini',
             'Saudi Arabia / السعودية': 'Saudi',
             'Taiwan': 'Taiwan',
             'Kazakhstan': 'Kazakhstan',
             'Australia': 'Australia',
             'Türkiye': 'Turkey',
             'Ukraine': 'Ukraine',
             'Nicaragua': 'Nicaragua',
             'Barbados': 'Barbados',
             'Bahamas': 'Bahamas',
             'Brasil': 'Brazil',
             'Lietuva': 'Lithuania',
             'Moldova': 'Moldova',
             'Haiti': 'Haiti',
             'South Korea': 'South Korea',
             'Norge': 'Norge',
             'Seychelles': '',
             'Andorra': 'Andorra',
             'United States of America': 'USA',
             'México': 'Mexico',
             'Armenia': 'Armenia',
             'Trinidad and Tobago': 'Trinidad and Tobago',
             'Afghanistan': 'Afghanistan',
             'Belgium': 'Belgium',
             'Ireland': 'Ireland',
             'Nederland': 'Nederland',
             'Sierra Leone': 'Sierra Leone',
             'Deutschland': 'Germany',
             'Nauru': 'Nauru',
             'România': 'Romania',
             'Solomon Islands': 'Solomon Islands',
               'Poland': 'Poland',
               'Brazil': 'Brazil',
               'Germany': 'Germany',
               'Sweden': 'Sweden',
               'Iceland': 'Iceland'}